services:
  - type: web
    name: moamoa-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: SUPABASE_DB_URL
        sync: false
      - key: SUPABASE_DB_USERNAME
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_JWKS_URI
        sync: false
      - key: SUPABASE_ISSUER_URI
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: AI_SERVER_BASE_URL
        sync: false
